   
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


import os
from sys import displayhook
import threading
from pathlib import Path
from tkinter import *


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("839x640")
window.configure(bg = "#FFFFFF")
class App(threading.Thread):
    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 640,
        width = 839,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        419.0,
        316.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=311.0,
        y=562.0,
        width=220.0,
        height=59.0
    )

    canvas.create_text(
        303.0,
        40.0,
        anchor="nw",
        text="alexa",
        fill="#F8FD1A",
        font=("None", int(36.0))
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png")
    )
    entry_bg_1 = canvas.create_image(
        419.5,
        445.0,
        image=entry_image_1
    )
    entry_1_str = StringVar()
    entry_1 = Entry(
        bd=0,
        bg="#80C5F7",
        highlightthickness=0,
        textvariable=entry_1_str
    )
    entry_1.place(
        x=0.0,
        y=412.0,
        width=839.0,
        height=64.0
    )

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=196.0,
        y=494.0,
        width=450.0,
        height=45.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png")
    )
    entry_bg_2 = canvas.create_image(
        419.5,
        256.5,
        image=entry_image_2
    )
    entry_2 = Text(
        bd=0,
        bg="#D5CFCF",
        highlightthickness=0
    )
    entry_2.place(
        x=0.0,
        y=117.0,
        width=839.0,
        height=277.0
        )
window.resizable(False, False)
#window.mainloop()