
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


import os
from sys import displayhook
import threading
from pathlib import Path
from tkinter import *


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("360x640")
window.configure(bg = "#FFFFFF")

class App(threading.Thread):
     

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 640,
        width = 360,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    image_image_1 = PhotoImage(
        file=relative_to_assets("image_1.png"))
    image_1 = canvas.create_image(
        180.0,
        320.0,
        image=image_image_1
    )

    button_image_1 = PhotoImage(
        file=relative_to_assets("button_1.png"))
    button_1 = Button(
        image=button_image_1,
        borderwidth=0,
        highlightthickness=0,
        command=lambda: print("button_1 clicked"),
        relief="flat"
    )
    button_1.place(
        x=118.0,
        y=565.0,
        width=114.0,
        height=50.0
    )

    canvas.create_text(
        63.0,
        40.0,
        anchor="nw",
        text="alexa",
        fill="#F52222",
        font=("None", int(36.0))
    )

    entry_image_1 = PhotoImage(
        file=relative_to_assets("entry_1.png")
    )
    entry_bg_1 = canvas.create_image(
        190.0,
        442.5,
        image=entry_image_1
    )
    
    entry_1_str = StringVar()
    entry_1 = Entry(
    bd=0,
    bg="#80C5F7",
    highlightthickness=0,
    textvariable=entry_1_str
    )
    entry_1.place(
        x=63.0,
        y=412.0,
        width=254.0,
        height=59.0
    )
    

    button_image_2 = PhotoImage(
        file=relative_to_assets("button_2.png"))
    button_2 = Button(
        image=button_image_2,
        borderwidth=0,
        highlightthickness=0,
        command=lambda:print("button 2 clicked"),
        relief="flat"
    )
    button_2.place(
        x=118.0,
        y=495.0,
        width=114.0,
        height=48.0
    )

    entry_image_2 = PhotoImage(
        file=relative_to_assets("entry_2.png")
    )
    entry_bg_2 = canvas.create_image(
        190.0,
        329.0,
        image=entry_image_2
    )
    entry_2 = Text(
        bd=0,
        bg="#D5CFCF",
        highlightthickness=0
    )
    entry_2.place(
        x=63.0,
        y=265.0,
        width=254.0,
        height=126.0
    )

    image_image_2 = PhotoImage(
        file=relative_to_assets("image_2.png"))
    image_2 = canvas.create_image(
        179.0,
        174.0,
        image=image_image_2
    )
    
window.resizable(False, False)
#window.mainloop()